Fix: Spell-check hook handles deleted files

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -14,22 +14,24 @@ set -u
 exec < /dev/tty
 
 for f in $(git diff --name-only --cached | grep content/); do
-    echo "Spell-checking ${f} ... "
-    aspell \
-        --mode=sgml \
-        --add-sgml-skip={ulink,code,literal,firstname,parameter,option,package,replaceable,programlisting,userinput,screen,filename,command,computeroutput,abbrev,accel,orgname,surname,foreignphrase,acronym,hardware,keycap,systemitem,application} \
-        --lang="en" \
-        --home-dir=. \
-        check "${f}"
-    if [[ $? != 0 ]]; then
-        # Unfortunately, this never happens.
-        # --> https://github.com/GNUAspell/aspell/issues/598
-        echo 'Aborted.'
-        exit 1
-    else
-        if ! git diff --quiet "${f}"; then
-            echo "Staging changes to ${f}"
-            git add "${f}"
+    if [ -f "${f}" ]; then
+        echo "Spell-checking ${f} ... "
+        aspell \
+            --mode=sgml \
+            --add-sgml-skip={ulink,code,literal,firstname,parameter,option,package,replaceable,programlisting,userinput,screen,filename,command,computeroutput,abbrev,accel,orgname,surname,foreignphrase,acronym,hardware,keycap,systemitem,application} \
+            --lang="en" \
+            --home-dir=. \
+            check "${f}"
+        if [[ $? != 0 ]]; then
+            # Unfortunately, this never happens.
+            # --> https://github.com/GNUAspell/aspell/issues/598
+            echo 'Aborted.'
+            exit 1
+        else
+            if ! git diff --quiet "${f}"; then
+                echo "Staging changes to ${f}"
+                git add "${f}"
+            fi
         fi
     fi
 done
